### PR TITLE
Toolkit creation

### LINKED ISSUE #1: First Toolkit creation from Template
#### Description:

First Toolkit creation from Template

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1

### CODE REVIEW

**Comment by LightosTomJ** [comment]
Looks good to me

**Comment by LightosTomJ** [comment]
I'm not seeing the merge branch option. Do I need to re-open this pull request?

**Comment by alelom** [comment]
@LightosTomJ if you re-approve you can then click on `Rebase and merge`:

image

if, after approving, that's still greyed out for you, it means we need to elevate your permissions.

**Comment by LightosTomJ** [comment]
I see no approve button, so I assume that you need to elevate my permissions.

**Comment by alelom** [comment]
> I see no approve button, so I assume that you need to elevate my permissions.

@al-fisher can you do that please?

**Comment by al-fisher** [comment]
Hey @LightosTomJ 
I have now set up permissions so you, @alelom and @pawelbaran have ability to merge, following approval.

**Review by LightosTomJ — APPROVED** [review]
Looks good to me.

**Pull request merged**
